task-4 repo. migrations. dataset
ozonmp/ise-car-api pull request #3
Opened 2021-11-10 21:40 UTC by mmeirink

2021-11-13 06:19 UTC, Maklayna requested changes

2021-11-13 06:19 UTC, Maklayna commented on internal/api/add_car.go
> +		TotalPrice: float64(req.GetTotalPrice()),
float плохо подходит для денег

2021-11-13 06:19 UTC, Maklayna commented on internal/app/repo/event.go
> +	query := sq.Update("car_event").PlaceholderFormat(sq.Dollar).
PlaceholderFormat(sq.Dollar) можно один раз определить для экземпляра а потом использовать его

2021-11-13 06:19 UTC, Maklayna commented on internal/app/repo/event.go
> +	s, args, err := query.ToSql()
проверка ошибки?

2021-11-13 06:19 UTC, Maklayna commented on internal/repo/repo.go
> +	rows, err := query.QueryContext(ctx)
А зачем раньше использовались запросы через  db а тут через sq?

2021-11-13 06:19 UTC, Maklayna commented on internal/repo/repo.go
> +		return 0, sql.ErrNoRows
так не стоит делать, допустим при синтаксической ошибке в запросе получится закрытый набор строк, и ошибка, он не sql.ErrNoRows + надо всегда проверять rows.Err() после прохода по курсору

2021-11-16 09:14 UTC, Maklayna approved these changes

2021-11-16 17:59 UTC, mmeirink commented on internal/app/repo/event.go
> +					  )
Он нужен, чтобы сделать order by и limit

2021-11-16 17:59 UTC, mmeirink commented on internal/app/repo/event.go
> +		isAcquired, err := database.AcquireTryLock(ctx, tx, 0)
Ага, вынесла

2021-11-16 18:00 UTC, merged